=== jghiloni/resume-2023/public/schema/resume.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "resume.schema.json",
  "title": "Resume",
  "description": "My resumé schema. There are many resumés like it, but this one is mine",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "phone": { "type": "string", "pattern": "^[1-9][0-9]{9}$" },
    "email": { "type": "string" },
    "linkedin": { "type": "string" },
    "github": { "type": "string" },
    "sections": { "type": "array", "items": { "$ref": "#/$defs/section" } }
  },
  "$defs": {
    "link": {
      "type": "object",
      "properties": {
        "href": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "line": {
      "oneOf": [
        { "type": "string" },
        {
          "type": "array",
          "items": {
            "contains": {
              "allOf": [{ "type": "string" }, { "$ref": "#/$defs/link" }]
            }
          }
        }
      ]
    },
    "text": {
      "type": "object",
      "properties": {
        "variant": {
          "enum": ["paragraph", "lines", "list"]
        },
        "text": {
          "anyOf": [
            { "$ref": "#/$defs/line" },
            { "type": "array", "items": { "$ref": "#/$defs/line" } }
          ]
        }
      }
    },
    "section": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "items": { "type": "array", "items": { "$ref": "#/$defs/sectionitem" } }
      }
    },
    "sectionitem": {
      "type": "object",
      "properties": {
        "header": {
          "type": "array",
          "items": {
            "contains": {
              "anyOf": [{ "type": "string" }, { "$ref": "#/$defs/link" }]
            }
          }
        },
        "body": {
          "oneOf": [
            {
              "$ref": "#/$defs/text"
            },
            {
              "type": "array",
              "items": { "$ref": "#/$defs/skill" }
            }
          ]
        },
        "required": ["body"]
      }
    },
    "skill": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "first_used": { "type": "integer", "minimum": 1997 },
        "last_used": { "type": "integer", "minimum": 1997 },
        "experience": {
          "enum": [
            "Beginner",
            "Intermediate",
            "Advanced",
            "Expert",
            "Out of Practice"
          ]
        }
      }
    }
  }
}

=== jghiloni/resume-2023/public/resume.json
{
  "$schema": "./schema/resume.schema.json",
  "name": "Josh Ghiloni",
  "phone": "3035905427",
  "email": "ghiloni@gmail.com",
  "linkedin": "https://www.linkedin.com/in/joshghiloni/",
  "github": "https://github.com/gideaworx",
  "sections": [
    {
      "name": "Objective",
      "items": [
        {
          "body": {
            "variant": "paragraph",
            "text": "I strive to use my 25+ years of professional experience in software engineering to create solutions that delight my stakeholders, mentor the next generation of technologist professionals, lead teams in an effective way, and learn from my mistakes and my colleagues."
          }
        }
      ]
    },
    {
      "name": "Education",
      "items": [
        {
          "header": [
            "Case Western Reserve University",
            "Bachelor of Science, Computer Science",
            "1999—2003"
          ],
          "body": {
            "variant": "list",
            "text": [
              "Courses focused on theoretical computer science, hybrid systems, autonomous robotics",
              "Broad focus on humanities and liberal arts, with extensive coursework in German and music",
              "Activities: Phi Kappa Theta fraternity, Case Men's Glee Club, Symphonic and Jazz Bands, Pit orchestra for multiple student-produced musicals"
            ]
          }
        }
      ]
    },
    {
      "name": "Experience",
      "items": [
        {
          "header": [
            "Principal Software Engineer",
            {
              "href": "https://realtor.com",
              "text": "realtor.com"
            },
            "2022—Present"
          ],
          "body": {
            "variant": "list",
            "text": [
              "Introduced uptime monitoring for various sections of the site, first through Uptrends, then through New Relic",
              "Prepared executive-level quarterly reports, cross-referencing uptime percentages with user-impacting incidents",
              "Assisted a team from a recent acquisition in migrating their site onto realtor.com infrastructure. This included writing a super-low-latency router, redirecting approximately 30,000 URLs to the new format in sub-20ms time using AWS CloudFront and DynamoDB",
              "As teams migrated from Jenkins-based CI/CD and native AWS-based infrastructure to cloud-native CI/CD with CircleCI and ArgoCD and Kubernetes-based infrastructure, I assisted many teams, including my own, with the transition, using my extensive experience with Kubernetes and CI/CD solutions",
              "Migrated many internal tools from bespoke, tightly coupled interfaces to more generic, cloud-native solutions",
              "Mentored my team of young engineers on cloud-native and enterprise software patterns, as well as how to navigate the internal politics of a medium-sized enterprise which was, for most of them, their first full-time job",
              "As part of the Quality Ops Leadership Team, I introduced new technologies and brought an engineer's perspective to a team mostly consisting of non-technical managers"
            ]
          }
        },
        {
          "header": [
            "Founder and Sole Proprietor",
            "Ghiloni Ideaworx",
            "2022—Present"
          ],
          "body": {
            "variant": "paragraph",
            "text": [
              "Ghiloni Ideaworx is an umbrella organization for my various independent endeavors, focused on open source software, independent software consulting, and custom woodworking commissions. View my open-source portfolio",
              {
                "href": "https://github.com/gideaworx",
                "text": "here."
              }
            ]
          }
        },
        {
          "header": [
            "Staff Solutions Architect",
            "VMware Tanzu/Pivotal Labs",
            "2017—2022"
          ],
          "body": {
            "variant": "list",
            "text": [
              "Led and participated in post-sales professional services engagements for the VMware Tanzu product line (formerly known as Pivotal Cloud Foundry). These engagements included product education, implementing automated infrastructure deployment, building structured product backlogs, and driving cultural transformation around building balanced product teams, implementing a culture of test-driven development, and other needs as deemed necessary per situation",
              "Developed tools to help Solutions Architects migrate the contents of one Tanzu Application Service installation to another",
              "Led an internal SRE team for a pilot managed service offering for a customer, with automation and observability refined to a degree to which we received no incident pages in the final 18 months of my involvement"
            ]
          }
        },
        {
          "header": [
            "Principal Consultant",
            "ECS Team (now part of CGI)",
            "2012—2017"
          ],
          "body": {
            "variant": "list",
            "text": [
              "Member of a boutique consulting firm based in Denver, CO, acquired by CGI in 2017",
              "Lead technical architect for Connect for Health Colorado, Colorado's implementation of the Affordable Care Act's Healthcare Exchange. We had the distinction of being the only state whose exchange did not crash on day 1. Developed highly available infrastructure based on Oracle's SOA Stack, and custom solutions to provide EDI transfer between the exchange and insurance providers, from 2012—2014",
              "Acted as an Enterprise Architect with DigitalGlobe (now Maxar), helping modernize their software stack powering the ground systems for their WorldView 4 satellite. Implemented a polyglot app-to-app authentication and authorization system using OAuth 2 for apps deployed to Cloud Foundry (both open source and Pivotal-branded variants)",
              "Participated in Pivotal Cloud Foundry Solutions engagements as a Pivotal Ready Partner (see above for an in-depth description)"
            ]
          }
        },
        {
          "header": ["Advisory Software Engineer", "IBM", "2003—2012"],
          "body": {
            "variant": "list",
            "text": [
              "QA and Development for IBM Portal Personalization and IBM WebSphere Portal Document Manager",
              "Integrated Lotus Quickr with IBM's Enterprise Content Management Portfolio",
              "Implemented multi-tenancy for IBM SmartCloud / IBM Connections"
            ]
          }
        }
      ]
    },
    {
      "name": "Programming Languages",
      "items": [
        {
          "body": [
            {
              "name": "Go",
              "first_used": 2015,
              "last_used": 9999,
              "experience": "Expert"
            },
            {
              "name": "Node.js (Javascript and Typescript)",
              "first_used": 2017,
              "last_used": 9999,
              "experience": "Expert"
            },
            {
              "name": "Bash",
              "first_used": 1999,
              "last_used": 9999,
              "experience": "Expert"
            },
            {
              "name": "Java",
              "first_used": 2003,
              "last_used": 9999,
              "experience": "Advanced"
            },
            {
              "name": "Python",
              "first_used": 2002,
              "last_used": 9999,
              "experience": "Intermediate"
            },
            {
              "name": "C++",
              "first_used": 1999,
              "last_used": 2010,
              "experience": "Out of Practice"
            },
            {
              "name": ".Net",
              "first_used": 2001,
              "last_used": 2014,
              "experience": "Out of Practice"
            }
          ]
        }
      ]
    },
    {
      "name": "Application Frameworks",
      "items": [
        {
          "body": [
            {
              "name": "Helm",
              "first_used": 2019,
              "last_used": 9999,
              "experience": "Expert"
            },
            {
              "name": "React.js",
              "first_used": 2018,
              "last_used": 9999,
              "experience": "Advanced"
            },
            {
              "name": "Spring Boot",
              "first_used": 2014,
              "last_used": 9999,
              "experience": "Advanced"
            },
            {
              "name": "Flask",
              "first_used": 2022,
              "last_used": 9999,
              "experience": "Beginner"
            }
          ]
        }
      ]
    },
    {
      "name": "CI/CD Frameworks",
      "items": [
        {
          "body": [
            {
              "name": "CircleCI",
              "first_used": 2021,
              "last_used": 9999,
              "experience": "Advanced"
            },
            {
              "name": "ArgoCD",
              "first_used": 2021,
              "last_used": 9999,
              "experience": "Intermediate"
            },
            {
              "name": "Concourse CI",
              "first_used": 2015,
              "last_used": 9999,
              "experience": "Expert"
            },
            {
              "name": "Github Actions",
              "first_used": 2021,
              "last_used": 9999,
              "experience": "Intermediate"
            },
            {
              "name": "Jenkins",
              "first_used": 2001,
              "last_used": 2022,
              "experience": "Intermediate"
            }
          ]
        }
      ]
    },
    {
      "name": "Observability Tools",
      "items": [
        {
          "body": [
            {
              "name": "Prometheus",
              "first_used": 2018,
              "last_used": 2022,
              "experience": "Advanced"
